### ISSUE TITLE
Android Crash

### ISSUE THREAD

**Issue by renatomserra** [vtr0n/react-native-yandex-mobile-ads#25]
On iOS things seem to be running smoothly, on android i get the following crash on load.

```
02-18 12:34:30.452   601   601 W ActivityManager: Unbind failed: could not find connection for android.app.LoadedApk$ServiceDispatcher$InnerConnection@50e8b86
02-18 12:34:30.453  1619  1619 W A       : Can't get WAA status for Mavatar!
02-18 12:34:30.453  1619  1619 W A       : java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.apps.tiktok.dataservice.z.b(PG:1)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.apps.tiktok.dataservice.at.a(PG:1)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.apps.tiktok.tracing.ec.a(PG:2)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.aj.a(PG:2)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.ac.apply(PG:1)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.h.e(PG:2)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.j.run(PG:9)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.bf.execute(PG:1)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.d.i(PG:1)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.d.l(PG:12)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.d.n(PG:2)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.i.f(PG:1)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.common.util.concurrent.j.run(PG:12)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.android.libraries.i.ae.run(PG:1)
02-18 12:34:30.453  1619  1619 W A       : 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
02-18 12:34:30.453  1619  1619 W A       : 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.android.libraries.i.l.run(PG:2)
02-18 12:34:30.453  1619  1619 W A       : 	at com.google.android.libraries.i.q.run(PG:4)
02-18 12:34:30.453  1619  1619 W A       : 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by renatomserra** [comment]
Found it was an issue with another import of google gms
